# -*- coding: utf-8 -*-
"""infosys_project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tVPP4hzWUWrlM1O24sdO_ITxs83ysm6u
"""

import pandas as pd
import numpy as np
df = pd.read_csv('flights.csv')

df.shape

df.head()

df.info()

df.isnull().sum().sort_values(ascending=False)

df.isnull().sum().sort_values(ascending=False)

# Drop unnecessary column
df = df.drop(columns=["TAIL_NUMBER"])

# Drop very small missing rows
df = df.dropna(subset=["SCHEDULED_TIME"])

# Fill delay nulls if any
df["DEPARTURE_DELAY"] = df["DEPARTURE_DELAY"].fillna(0)

# Final check
print(df.isnull().sum())

df['CANCELLATION_REASON'] = df['CANCELLATION_REASON'].fillna('None')



df['CANCELLATION_REASON'].isnull().sum()

delay_cols = [
    'AIRLINE_DELAY',
    'WEATHER_DELAY',
    'AIR_SYSTEM_DELAY',
    'SECURITY_DELAY',
    'LATE_AIRCRAFT_DELAY'
]

df[delay_cols] = df[delay_cols].fillna(0)

df[delay_cols].isnull().sum()

time_cols = [
    'ARRIVAL_DELAY',
    'DEPARTURE_DELAY',
    'ELAPSED_TIME',
    'AIR_TIME'
]

df[time_cols] = df[time_cols].fillna(0)

df[time_cols].isnull().sum()

df['FlightDate'] = pd.to_datetime(df[['YEAR', 'MONTH', 'DAY']])

df['FlightDate'].dtype

df['CANCELLED'] = df['CANCELLED'].astype('int8')
df['DIVERTED'] = df['DIVERTED'].astype('int8')

df['AIRLINE'] = df['AIRLINE'].astype('category')

df['MONTH'] = df['FlightDate'].dt.month
df['DAY_OF_WEEK'] = df['FlightDate'].dt.day_name()

df['ROUTE'] = df['ORIGIN_AIRPORT'].astype(str) + " → " + df['DESTINATION_AIRPORT'].astype(str)

df.isnull().sum().sort_values(ascending=False)



df = df.dropna(subset=[
    'DISTANCE',
    'AIRLINE',
    'ORIGIN_AIRPORT',
    'DESTINATION_AIRPORT'
])

df.loc[df['CANCELLED'] == 1, time_cols] = 0

df.isnull().sum().sort_values(ascending=False)

time_cols = [
    'WHEELS_ON', 'TAXI_IN', 'ARRIVAL_TIME',
    'TAXI_OUT', 'WHEELS_OFF', 'DEPARTURE_TIME'
]

df.loc[df['CANCELLED'] == 1, time_cols] = 0

df[time_cols].isnull().sum()

df.loc[df['DIVERTED'] == 1, time_cols] = 0

df[time_cols].isnull().sum()

df = df.drop(columns=['ROUTE'])

df.isnull().sum().sort_values(ascending=False)

time_cols = [
    'WHEELS_ON', 'TAXI_IN', 'ARRIVAL_TIME',
    'TAXI_OUT', 'WHEELS_OFF', 'DEPARTURE_TIME'
]

df.loc[df['CANCELLED'] == 1, time_cols] = 0
df.loc[df['DIVERTED'] == 1, time_cols] = 0

df.isnull().sum()

df.isnull().sum().sum()

df.to_csv("cleaned_airfly_data.csv", index=False)

import os
os.listdir()

from google.colab import files
files.download("cleaned_airfly_data (1).csv")

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

sns.set_style("whitegrid")
plt.rcParams["figure.figsize"] = (10,6)

# Load your cleaned dataset
df = pd.read_csv("cleaned_airfly_data.csv")

print("Shape:", df.shape)
print("\nColumns:\n", df.columns)

print(df.columns)

top_airlines = df["AIRLINE"].value_counts().head(10)

plt.figure()
top_airlines.sort_values().plot(kind="barh")
plt.title("Top 10 Airlines by Flight Volume")
plt.xlabel("Number of Flights")
plt.ylabel("Airline")
plt.tight_layout()
plt.show()

top_routes = df["ROUTE"].value_counts().head(10)

plt.figure()
sns.barplot(x=top_routes.values, y=top_routes.index)
plt.title("Top 10 Busiest Routes")
plt.xlabel("Number of Flights")
plt.ylabel("Route")
plt.tight_layout()
plt.show()

monthly_flights = df.groupby("MONTH").size()

plt.figure()
monthly_flights.plot(marker="o")
plt.title("Monthly Flight Distribution")
plt.xlabel("Month")
plt.ylabel("Number of Flights")
plt.tight_layout()
plt.show()

day_flights = df.groupby("DAY_OF_WEEK").size()

plt.figure()
day_flights.plot(kind="bar")
plt.title("Flights by Day of Week")
plt.xlabel("Day of Week")
plt.ylabel("Number of Flights")
plt.tight_layout()
plt.show()

plt.figure()
sns.histplot(df["DEPARTURE_DELAY"], bins=50)
plt.title("Departure Delay Distribution")
plt.xlabel("Delay (Minutes)")
plt.ylabel("Frequency")
plt.tight_layout()
plt.show()

avg_delay_airline = (
    df.groupby("AIRLINE")["DEPARTURE_DELAY"]
    .mean()
    .sort_values(ascending=False)
    .head(10)
)

plt.figure()
avg_delay_airline.plot(kind="bar")
plt.title("Top 10 Airlines by Average Departure Delay")
plt.xlabel("Airline")
plt.ylabel("Average Delay (Minutes)")
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

delay_cols = [
    "AIRLINE_DELAY",
    "WEATHER_DELAY",
    "AIR_SYSTEM_DELAY",
    "LATE_AIRCRAFT_DELAY"
]

airline_delay = (
    df.groupby("AIRLINE")[delay_cols]
    .mean()
    .head(10)
)

plt.figure()
airline_delay.plot(kind="bar", stacked=True)
plt.title("Delay Causes by Airline")
plt.xlabel("Airline")
plt.ylabel("Average Delay (Minutes)")
plt.tight_layout()
plt.show()

df["DEPARTURE_HOUR"] = df["SCHEDULED_DEPARTURE"] // 100

plt.figure(figsize=(12,6))

sns.boxplot(
    x="DEPARTURE_HOUR",
    y="DEPARTURE_DELAY",
    data=df
)

plt.title("Departure Delay Distribution by Hour of Day")
plt.xlabel("Departure Hour")
plt.ylabel("Departure Delay (Minutes)")
plt.tight_layout()
plt.show()

#

#

#

#

#

#

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

sns.set(style="whitegrid")

df = pd.read_csv("cleaned_airfly_data (1).csv")

df.head()

print("Shape of dataset:", df.shape)

df.info()

df.describe()

df.columns

top_routes = df['ROUTE'].value_counts().head(10)

plt.figure(figsize=(10,6))
top_routes.plot(kind='bar')

plt.title("Top 10 Busiest Flight Routes")
plt.xlabel("Route")
plt.ylabel("Number of Flights")
plt.xticks(rotation=45)
plt.show()

monthly_flights = df['MONTH'].value_counts().sort_index()

plt.figure(figsize=(8,5))
monthly_flights.plot(kind='line', marker='o')

plt.title("Monthly Flight Trend")
plt.xlabel("Month")
plt.ylabel("Number of Flights")
plt.show()

cancel_reason = df['CANCELLATION_REASON'].value_counts()

plt.figure(figsize=(6,6))
cancel_reason.plot(kind='pie', autopct='%1.1f%%')

plt.title("Flight Cancellation Reasons")
plt.ylabel("")
plt.show()

plt.figure(figsize=(8,5))

sns.histplot(df['DEPARTURE_DELAY'], bins=50)

plt.title("Departure Delay Distribution")
plt.xlabel("Delay (minutes)")
plt.ylabel("Frequency")
plt.show()

plt.figure(figsize=(12,6))

sns.boxplot(x='AIRLINE', y='DEPARTURE_DELAY', data=df)

plt.title("Delay Distribution by Airline")
plt.xlabel("Airline")
plt.ylabel("Departure Delay")
plt.show()

plt.figure(figsize=(8,5))

sns.scatterplot(x='DISTANCE', y='DEPARTURE_DELAY', data=df)

plt.title("Distance vs Departure Delay")
plt.xlabel("Distance")
plt.ylabel("Delay")
plt.show()

route_delay = df.pivot_table(
    values='DEPARTURE_DELAY',
    index='ORIGIN_AIRPORT',
    columns='DESTINATION_AIRPORT',
    aggfunc='mean'
)

plt.figure(figsize=(12,8))

sns.heatmap(route_delay, cmap="coolwarm")

plt.title("Airport Route Delay Heatmap")
plt.show()

airport_delay = df.groupby('ORIGIN_AIRPORT')['DEPARTURE_DELAY'].mean().sort_values(ascending=False).head(10)

plt.figure(figsize=(10,6))
airport_delay.plot(kind='barh')

plt.title("Top Airports with Highest Average Delay")
plt.xlabel("Average Delay")
plt.ylabel("Airport")
plt.show()

!pip install folium

import pandas as pd
import folium

df = pd.read_csv("cleaned_airfly_data (1).csv")

df.head()

airport_coords = {
    "ATL":[33.6407,-84.4277],
    "LAX":[33.9416,-118.4085],
    "ORD":[41.9742,-87.9073],
    "DFW":[32.8998,-97.0403],
    "DEN":[39.8561,-104.6737],
    "JFK":[40.6413,-73.7781],
    "SFO":[37.6213,-122.3790],
    "SEA":[47.4502,-122.3088],
    "LAS":[36.0840,-115.1537],
    "MCO":[28.4312,-81.3081],
    "PHX":[33.4342,-112.0116],
    "IAH":[29.9902,-95.3368]
}

busiest_airports = df['ORIGIN_AIRPORT'].value_counts().head(10)

map1 = folium.Map(location=[39.5,-98.35], zoom_start=4)

for airport, flights in busiest_airports.items():

    if airport in airport_coords:

        lat, lon = airport_coords[airport]

        folium.CircleMarker(
            location=[lat, lon],
            radius=flights/500,
            popup=f"{airport} Flights: {flights}",
            color="blue",
            fill=True,
            fill_color="blue"
        ).add_to(map1)

map1

airport_delay = df.groupby('ORIGIN_AIRPORT')['DEPARTURE_DELAY'].mean()

map2 = folium.Map(location=[39.5,-98.35], zoom_start=4)

for airport, delay in airport_delay.items():

    if airport in airport_coords:

        lat, lon = airport_coords[airport]

        folium.CircleMarker(
            location=[lat, lon],
            radius=6,
            popup=f"{airport} Avg Delay: {delay:.2f} minutes",
            color="red",
            fill=True,
            fill_color="red"
        ).add_to(map2)

map2

!!

!!

!!

!pip install streamlit seaborn
!npm install -g localtunnel

from google.colab import files
files.upload()

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# import streamlit as st
# import pandas as pd
# import plotly.express as px
# 
# st.set_page_config(layout="wide")
# 
# # -------------------------
# # LOAD DATA
# # -------------------------
# df = pd.read_csv("/content/cleaned_airfly_data.csv")
# df.columns = df.columns.str.lower().str.strip()
# df = df.loc[:, ~df.columns.duplicated()]
# 
# # -------------------------
# # 👤 PROFILE SIDEBAR
# # -------------------------
# st.sidebar.markdown("## 👤 Profile")
# 
# try:
#     st.sidebar.image("/content/profile1.png", width=130)
# except:
#     st.sidebar.warning("Upload profile1.png")
# 
# st.sidebar.markdown("**Ullas S**")
# st.sidebar.markdown("[📧 ullasgowda1917@gmail.com](mailto:ullasgowda1917@gmail.com)")
# st.sidebar.markdown("📱 636862848")
# 
# st.sidebar.markdown("---")
# 
# # -------------------------
# # FILTERS
# # -------------------------
# st.sidebar.header("🔍 Filters")
# 
# airline = st.sidebar.multiselect("Airline", sorted(df['airline'].dropna().unique()))
# month = st.sidebar.multiselect("Month", sorted(df['month'].dropna().unique()))
# 
# day = st.sidebar.multiselect(
#     "Day of Week",
#     sorted(df['day_of_week'].dropna().unique()) if 'day_of_week' in df.columns else []
# )
# 
# route = st.sidebar.multiselect(
#     "Route",
#     sorted(df['route'].dropna().unique()) if 'route' in df.columns else []
# )
# 
# airport = st.sidebar.multiselect(
#     "Origin Airport",
#     sorted(df['origin_airport'].dropna().unique())
# )
# 
# hour = st.sidebar.slider("Hour Range", 0, 23, (0, 23))
# 
# delay_range = st.sidebar.slider(
#     "Delay Range",
#     int(df['arrival_delay'].min()),
#     int(df['arrival_delay'].max()),
#     (0, 100)
# )
# 
# cancel_filter = st.sidebar.selectbox("Cancelled Flights", ["All", "Yes", "No"])
# 
# top_n = st.sidebar.slider("Top N", 5, 20, 10)
# 
# metric = st.sidebar.radio("Analyze By", ["Flights", "Delay", "Cancellations"])
# 
# # -------------------------
# # APPLY FILTERS
# # -------------------------
# if airline:
#     df = df[df['airline'].isin(airline)]
# 
# if month:
#     df = df[df['month'].isin(month)]
# 
# if day:
#     df = df[df['day_of_week'].isin(day)]
# 
# if route:
#     df = df[df['route'].isin(route)]
# 
# if airport:
#     df = df[df['origin_airport'].isin(airport)]
# 
# df = df[(df['hour'] >= hour[0]) & (df['hour'] <= hour[1])]
# df = df[(df['arrival_delay'] >= delay_range[0]) & (df['arrival_delay'] <= delay_range[1])]
# 
# if cancel_filter == "Yes":
#     df = df[df['cancelled'] == 1]
# elif cancel_filter == "No":
#     df = df[df['cancelled'] == 0]
# 
# # -------------------------
# # TITLE
# # -------------------------
# st.markdown("## ✈️ Flight Delay & Cancellation Dashboard")
# 
# # -------------------------
# # KPI METRICS
# # -------------------------
# c1, c2, c3, c4 = st.columns(4)
# 
# c1.metric("Flights", len(df))
# c2.metric("Avg Delay", round(df['arrival_delay'].mean(), 2))
# c3.metric("Max Delay", round(df['arrival_delay'].max(), 2))
# c4.metric("Cancellations", int(df['cancelled'].sum()))
# 
# # -------------------------
# # TABS
# # -------------------------
# tab1, tab2, tab3, tab4 = st.tabs(["Overview", "Delays", "Routes", "Map"])
# 
# # -------------------------
# # OVERVIEW
# # -------------------------
# with tab1:
#     col1, col2 = st.columns(2)
# 
#     if metric == "Flights":
#         values = df['airline'].value_counts().head(top_n)
#     elif metric == "Delay":
#         values = df.groupby('airline')['arrival_delay'].mean().sort_values(ascending=False).head(top_n)
#     else:
#         values = df.groupby('airline')['cancelled'].sum().sort_values(ascending=False).head(top_n)
# 
#     with col1:
#         fig1 = px.bar(values, title="Airline Analysis")
#         st.plotly_chart(fig1, use_container_width=True)
# 
#     with col2:
#         fig2 = px.line(df['hour'].value_counts().sort_index(), markers=True, title="Flights by Hour")
#         st.plotly_chart(fig2, use_container_width=True)
# 
#     fig3 = px.histogram(df, x="arrival_delay", title="Delay Distribution")
#     st.plotly_chart(fig3, use_container_width=True)
# 
# # -------------------------
# # DELAYS
# # -------------------------
# with tab2:
#     col3, col4 = st.columns(2)
# 
#     delay = df.groupby('airline')['arrival_delay'].mean().sort_values(ascending=False)
# 
#     with col3:
#         fig4 = px.bar(delay.head(top_n), title="Average Delay")
#         st.plotly_chart(fig4, use_container_width=True)
# 
#     with col4:
#         cols = ['airline_delay','weather_delay','air_system_delay','late_aircraft_delay']
#         cols = [c for c in cols if c in df.columns]
# 
#         if cols:
#             d = df[cols].sum()
#             fig5 = px.pie(values=d.values, names=d.index, title="Delay Causes")
#             st.plotly_chart(fig5, use_container_width=True)
# 
#     fig6 = px.box(df.sample(min(2000,len(df))), x='airline', y='arrival_delay')
#     st.plotly_chart(fig6, use_container_width=True)
# 
# # -------------------------
# # ROUTES
# # -------------------------
# with tab3:
#     col5, col6 = st.columns(2)
# 
#     with col5:
#         if 'route' in df.columns:
#             fig7 = px.bar(df['route'].value_counts().head(top_n), orientation='h')
#             st.plotly_chart(fig7, use_container_width=True)
# 
#     with col6:
#         fig8 = px.line(df.groupby('month')['cancelled'].sum(), markers=True)
#         st.plotly_chart(fig8, use_container_width=True)
# 
#     heat = df.groupby(['month','hour']).size().reset_index(name='count')
#     fig9 = px.density_heatmap(heat, x='hour', y='month', z='count')
#     st.plotly_chart(fig9, use_container_width=True)
# 
# # -------------------------
# # MAP
# # -------------------------
# with tab4:
#     st.subheader("🌍 Flight Map")
# 
#     map_style = st.selectbox("Map Style", ["open-street-map", "carto-positron"])
# 
#     airport_data = df.groupby('origin_airport').agg({
#         'arrival_delay':'mean',
#         'cancelled':'sum'
#     }).reset_index()
# 
#     counts = df['origin_airport'].value_counts().reset_index()
#     counts.columns = ['origin_airport','count']
# 
#     airport_data = airport_data.merge(counts, on='origin_airport')
# 
#     coords = {
#         "ATL": (33.6407, -84.4277),
#         "LAX": (33.9416, -118.4085),
#         "ORD": (41.9742, -87.9073),
#         "DFW": (32.8998, -97.0403),
#         "DEN": (39.8561, -104.6737),
#         "JFK": (40.6413, -73.7781),
#         "SFO": (37.6213, -122.3790),
#         "SEA": (47.4502, -122.3088)
#     }
# 
#     airport_data['lat'] = airport_data['origin_airport'].map(lambda x: coords.get(x,(None,None))[0])
#     airport_data['lon'] = airport_data['origin_airport'].map(lambda x: coords.get(x,(None,None))[1])
# 
#     airport_data = airport_data.dropna()
# 
#     fig10 = px.scatter_mapbox(
#         airport_data,
#         lat="lat",
#         lon="lon",
#         size="count",
#         color="arrival_delay",
#         hover_name="origin_airport",
#         zoom=3,
#         height=600
#     )
# 
#     fig10.update_layout(mapbox_style=map_style)
# 
#     st.plotly_chart(fig10, use_container_width=True)
# 
# # -------------------------
# # INSIGHTS
# # -------------------------
# st.subheader("📌 Insights")
# 
# st.write("""
# - Airlines show different delay patterns
# - Peak hours increase congestion
# - Weather is a major delay factor
# - Some routes dominate traffic
# - Cancellations vary across months
# """)

# 1. Install everything
!pip install streamlit pyngrok --quiet

# 2. Kill any running processes
!pkill -f streamlit
!pkill -f ngrok

# 3. Start Streamlit (background)
import os
os.system("streamlit run app.py --server.port 8501 &")

# 4. Wait (IMPORTANT)
import time
time.sleep(15)

# 5. Start ngrok (WITH AUTH)
from pyngrok import ngrok

# 👉 REPLACE with your token
ngrok.set_auth_token("3BZB56JEJemlSWCMyUjONQunWve_3waCZxP1XwZR3D5Xu7mWh")

public_url = ngrok.connect(8501)
print("🔗 Open this link:", public_url)